version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: viverra
    ports:
      - "4848:4848"
      - "5555:5555"
    volumes:
      - viverra-volume:/app

volumes:
  viverra-volume:
    external: false
